export default {
  content: [
    "./index.html",
    "./src/**/*.{html,js}",
    "./pages/**/*.{html,js}"
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "on-secondary-container": "#007070",
        "error": "#ba1a1a",
        "secondary-fixed": "#8cf3f3",
        "secondary-container": "#8cf3f3",
        "on-tertiary-fixed-variant": "#43474b",
        "primary-fixed-dim": "#a7c8ff",
        "tertiary-fixed-dim": "#c3c7cb",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#424751",
        "on-secondary-fixed-variant": "#004f4f",
        "on-error": "#ffffff",
        "inverse-surface": "#263142",
        "surface": "#f9f9ff",
        "tertiary": "#42474b",
        "secondary-fixed-dim": "#6fd7d6",
        "inverse-primary": "#a7c8ff",
        "surface-container-low": "#f0f3ff",
        "on-primary-container": "#c4d9ff",
        "background": "#f9f9ff",
        "surface-dim": "#cfdaf1",
        "surface-bright": "#f9f9ff",
        "surface-tint": "#0e5eaf",
        "on-tertiary-fixed": "#171c1f",
        "surface-container-high": "#dee8ff",
        "on-primary-fixed": "#001b3c",
        "secondary": "#006a6a",
        "outline": "#727783",
        "surface-container-highest": "#d8e3fa",
        "on-primary-fixed-variant": "#004788",
        "inverse-on-surface": "#ebf1ff",
        "primary-fixed": "#d5e3ff",
        "on-surface": "#111c2c",
        "on-secondary": "#ffffff",
        "primary": "#004688",
        "on-tertiary-container": "#d5d9dd",
        "surface-container": "#e7eeff",
        "outline-variant": "#c2c6d3",
        "tertiary-container": "#5a5f62",
        "on-error-container": "#93000a",
        "primary-container": "#0d5eaf",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#dfe3e7",
        "on-background": "#111c2c",
        "on-secondary-fixed": "#002020",
        "on-primary": "#ffffff",
        "surface-variant": "#d8e3fa"
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "sm": "0.25rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "margin": "32px",
        "sm": "12px",
        "gutter": "24px",
        "xs": "4px",
        "xl": "64px",
        "base": "8px",
        "lg": "40px",
        "md": "24px"
      },
      fontFamily: {
        "headline-md": ["Manrope"],
        "body-sm": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "label-sm": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg": ["Manrope"],
        "display-lg": ["Manrope"]
      },
      fontSize: {
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "14px", "fontWeight": "500"}],
        "label-md": ["14px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
